// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MONSTERDATA_BN2022W_MONSTERDATA_H_
#define FLATBUFFERS_GENERATED_MONSTERDATA_BN2022W_MONSTERDATA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 22 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 6,
             "Non-compatible flatbuffers version included");

namespace Bn2022w {
namespace MonsterData {

struct Monster;
struct MonsterBuilder;

struct MonsterList;
struct MonsterListBuilder;

struct Monster FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MonsterBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LABEL = 4,
    VT_NAME = 6,
    VT_HP = 8,
    VT_AP = 10,
    VT_DP = 12,
    VT_HAND = 14
  };
  const flatbuffers::String *label() const {
    return GetPointer<const flatbuffers::String *>(VT_LABEL);
  }
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  int16_t hp() const {
    return GetField<int16_t>(VT_HP, 0);
  }
  int16_t ap() const {
    return GetField<int16_t>(VT_AP, 0);
  }
  int16_t dp() const {
    return GetField<int16_t>(VT_DP, 0);
  }
  const flatbuffers::String *hand() const {
    return GetPointer<const flatbuffers::String *>(VT_HAND);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_LABEL) &&
           verifier.VerifyString(label()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int16_t>(verifier, VT_HP, 2) &&
           VerifyField<int16_t>(verifier, VT_AP, 2) &&
           VerifyField<int16_t>(verifier, VT_DP, 2) &&
           VerifyOffset(verifier, VT_HAND) &&
           verifier.VerifyString(hand()) &&
           verifier.EndTable();
  }
};

struct MonsterBuilder {
  typedef Monster Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_label(flatbuffers::Offset<flatbuffers::String> label) {
    fbb_.AddOffset(Monster::VT_LABEL, label);
  }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(Monster::VT_NAME, name);
  }
  void add_hp(int16_t hp) {
    fbb_.AddElement<int16_t>(Monster::VT_HP, hp, 0);
  }
  void add_ap(int16_t ap) {
    fbb_.AddElement<int16_t>(Monster::VT_AP, ap, 0);
  }
  void add_dp(int16_t dp) {
    fbb_.AddElement<int16_t>(Monster::VT_DP, dp, 0);
  }
  void add_hand(flatbuffers::Offset<flatbuffers::String> hand) {
    fbb_.AddOffset(Monster::VT_HAND, hand);
  }
  explicit MonsterBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Monster> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Monster>(end);
    return o;
  }
};

inline flatbuffers::Offset<Monster> CreateMonster(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> label = 0,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    int16_t hp = 0,
    int16_t ap = 0,
    int16_t dp = 0,
    flatbuffers::Offset<flatbuffers::String> hand = 0) {
  MonsterBuilder builder_(_fbb);
  builder_.add_hand(hand);
  builder_.add_name(name);
  builder_.add_label(label);
  builder_.add_dp(dp);
  builder_.add_ap(ap);
  builder_.add_hp(hp);
  return builder_.Finish();
}

inline flatbuffers::Offset<Monster> CreateMonsterDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *label = nullptr,
    const char *name = nullptr,
    int16_t hp = 0,
    int16_t ap = 0,
    int16_t dp = 0,
    const char *hand = nullptr) {
  auto label__ = label ? _fbb.CreateString(label) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto hand__ = hand ? _fbb.CreateString(hand) : 0;
  return Bn2022w::MonsterData::CreateMonster(
      _fbb,
      label__,
      name__,
      hp,
      ap,
      dp,
      hand__);
}

struct MonsterList FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MonsterListBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MONSTER_LIST = 4
  };
  const flatbuffers::Vector<flatbuffers::Offset<Bn2022w::MonsterData::Monster>> *monster_list() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<Bn2022w::MonsterData::Monster>> *>(VT_MONSTER_LIST);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MONSTER_LIST) &&
           verifier.VerifyVector(monster_list()) &&
           verifier.VerifyVectorOfTables(monster_list()) &&
           verifier.EndTable();
  }
};

struct MonsterListBuilder {
  typedef MonsterList Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_monster_list(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Bn2022w::MonsterData::Monster>>> monster_list) {
    fbb_.AddOffset(MonsterList::VT_MONSTER_LIST, monster_list);
  }
  explicit MonsterListBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<MonsterList> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<MonsterList>(end);
    return o;
  }
};

inline flatbuffers::Offset<MonsterList> CreateMonsterList(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Bn2022w::MonsterData::Monster>>> monster_list = 0) {
  MonsterListBuilder builder_(_fbb);
  builder_.add_monster_list(monster_list);
  return builder_.Finish();
}

inline flatbuffers::Offset<MonsterList> CreateMonsterListDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<Bn2022w::MonsterData::Monster>> *monster_list = nullptr) {
  auto monster_list__ = monster_list ? _fbb.CreateVector<flatbuffers::Offset<Bn2022w::MonsterData::Monster>>(*monster_list) : 0;
  return Bn2022w::MonsterData::CreateMonsterList(
      _fbb,
      monster_list__);
}

inline const Bn2022w::MonsterData::MonsterList *GetMonsterList(const void *buf) {
  return flatbuffers::GetRoot<Bn2022w::MonsterData::MonsterList>(buf);
}

inline const Bn2022w::MonsterData::MonsterList *GetSizePrefixedMonsterList(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<Bn2022w::MonsterData::MonsterList>(buf);
}

inline bool VerifyMonsterListBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Bn2022w::MonsterData::MonsterList>(nullptr);
}

inline bool VerifySizePrefixedMonsterListBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Bn2022w::MonsterData::MonsterList>(nullptr);
}

inline void FinishMonsterListBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Bn2022w::MonsterData::MonsterList> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMonsterListBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Bn2022w::MonsterData::MonsterList> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace MonsterData
}  // namespace Bn2022w

#endif  // FLATBUFFERS_GENERATED_MONSTERDATA_BN2022W_MONSTERDATA_H_
